---
title: "Phyloseq_16S"
output: github_document
date: "2026-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading libraries. If needed, use BiocManager to install them
```{r loading libraries, echo=FALSE, include=FALSE}
library("phyloseq")
library("ggplot2")
library("vegan")
library("readr")
library("tidyverse")
library("RColorBrewer")
```
```{r package versions, echo=FALSE}
packageDescription("phyloseq", fields = c("Package", "Version"))
packageDescription("ggplot2", fields = c("Package", "Version"))
packageDescription("vegan", fields = c("Package", "Version"))
packageDescription("readr", fields = c("Package", "Version"))
packageDescription("tidyverse", fields = c("Package", "Version"))
packageDescription("RColorBrewer", fields = c("Package", "Version"))
```

# Importing files and renaming ASVs
```{r importing files}
seqtab.nochim <- readr::read_csv("seqtab.nochim.csv")
seqtab.nochim <- as.data.frame(seqtab.nochim)
rownames(seqtab.nochim) <- seqtab.nochim[, 1]
seqtab.nochim <- seqtab.nochim[, -1]
colnames(seqtab.nochim) = paste0("ASV", 1:ncol(seqtab.nochim)) 

taxa <- read.csv("taxa.csv", row.names = 1)
row.names(taxa) = colnames(seqtab.nochim)
taxa <- as.matrix(taxa)

metadata <- read.csv("metadata.csv", stringsAsFactors = TRUE, row.names = 1)
```


# Building phyloseq object and removing Archaea sequences
```{r name}
ps.silva.nochim <- phyloseq(
  otu_table(seqtab.nochim, taxa_are_rows=FALSE),
  sample_data(metadata),
  tax_table(taxa))

ps <- subset_taxa(ps.silva.nochim, Kingdom !="Archaea")

ps
```

# Raryfing 
```{r raryfing}
set.seed(1)

counts <- sample_sums(ps)
sort(counts)

ps_withoutB6 <- subset_samples(ps, Code != "B6")

ps_withoutB6_rarified <- rarefy_even_depth(ps_withoutB6, sample.size = min(sample_sums(ps_withoutB6)),
                  rngseed = FALSE, replace = FALSE, trimOTUs = TRUE, verbose = TRUE)
```


# Samples colected from the foam will not be used in this manuscript, so we exclude them from the analysis
```{r excluding foam samples}
ps_withoutB6_rarified_withoutFOAM <- subset_samples(ps_withoutB6_rarified, Phase != "R1_Foam")
ps_withoutB6_rarified_withoutFOAM <- subset_samples(ps_withoutB6_rarified_withoutFOAM, Phase != "R2_Foam")
ps_withoutB6_rarified_withoutFOAM <- subset_samples(ps_withoutB6_rarified_withoutFOAM, Phase != "R3_Foam")
ps_withoutB6_rarified_withoutFOAM
```


# Alpha-diversity figure
```{r alpha}
cols <- c("Inoc" = "#4F81BD", "R1" = "#C06000", "R2" = "#632523", "R3" = "#4F6228")
cols2 <- c("Mid_Inoc" = "#4F81BD", "Hid_Inoc" = "#4F81BD", "R1" = "#C06000", "R2" = "#632523", "R3" = "#4F6228")

adiv <- data.frame(
  "Shannon" = phyloseq::estimate_richness(ps_withoutB6_rarified_withoutFOAM, measures = "Shannon"),
  "Simpson" = phyloseq::estimate_richness(ps_withoutB6_rarified_withoutFOAM, measures = "Simpson"),
  "Phase" = phyloseq::sample_data(ps_withoutB6_rarified_withoutFOAM)$Phase,
  "Reactor" = phyloseq::sample_data(ps_withoutB6_rarified_withoutFOAM)$Reactor_nmd)
head(adiv)

#png("figures_article/alpha_treatment.png", width = 7, height = 4, units = "in", res=300)
adiv %>%
  gather(key = metric, value = value, c("Simpson", "Shannon")) %>%
  mutate(metric = factor(metric, levels = c("Simpson", "Shannon"))) %>%
  ggplot(aes(x = Reactor, y = value)) +
  geom_boxplot(outlier.color = NA) +
  scale_colour_manual(values = cols) +
  scale_shape_manual(values= c(16, 17, 15, 3, 4, 8)) +
  geom_jitter(aes(color = Reactor, shape = Phase), height = 0, width = .2) +
  labs(x = "", y = "") +
  facet_wrap(~ metric, scales = "free") +
  theme(panel.background = element_rect(fill='white', colour='black'), 
        panel.grid.major = element_line(colour = "lightgrey"), text = element_text(size = 15), 
        axis.text.x = element_text(angle = 45, hjust = 1) )
#dev.off()
```
# Beta-diversity
```{r beta}
NMDS.bray <- ordinate(ps_withoutB6_rarified_withoutFOAM, "NMDS", "bray")
NMDS.bray

plot_NMDS <- plot_ordination(ps_withoutB6_rarified_withoutFOAM, NMDS.bray, type="samples", color="Reactor_nmd", shape = "Phase")

# plot with all samples 
#png("figures_article/NMDS_bray_elipse.png", width = 7, height = 4, units = "in", res=300)
plot_NMDS + 
  scale_colour_manual(values = cols) + 
  geom_point(alpha = 0.4, size = 3) + # Reduce alpha for better visibility of overlays
  scale_shape_manual(values= c(16, 17, 15, 3, 4, 8)) +
  stat_ellipse(geom = "polygon", alpha = 0.05, level = 0.95, aes(color = Phase), show.legend = TRUE, linetype = 1) +  # Add ellipses
  theme(panel.background = element_rect(fill='white', colour='black'), panel.grid.major = element_line(colour = "lightgrey"), text = element_text(size = 15))
#dev.off()


# plot without inoculum samples and environmental variables
# following this script: https://jkzorz.github.io/2020/04/04/NMDS-extras.html
ps_withoutB6_rarified_withoutFOAM_withoutINOC = subset_samples(ps_withoutB6_rarified_withoutFOAM, Reactor_nmd != "Inoc")

NMDS.bray2 <- ordinate(ps_withoutB6_rarified_withoutFOAM_withoutINOC, "NMDS", "bray")
NMDS.bray2

metadata_new <- read.csv2("metadata_new_mod.csv", stringsAsFactors = TRUE, row.names = 1)

en <- envfit(NMDS.bray2, metadata_new, permutations = 999, na.rm = TRUE)

data.scores <- as.data.frame(scores(NMDS.bray2)$sites)
data.scores$Phase <- ps_withoutB6_rarified_withoutFOAM_withoutINOC@sam_data$Phase
data.scores$Reactor <- ps_withoutB6_rarified_withoutFOAM_withoutINOC@sam_data$Reactor_nmd

en_coord_cont = as.data.frame(scores(en, "vectors")) * ordiArrowMul(en)

#png("figures_article/NMDS_bray_with_env.png", width = 7, height = 4, units = "in", res=300)
ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores, aes(colour = Reactor, shape = Phase), size = 3) + 
  scale_colour_manual(values = cols) + 
  scale_shape_manual(values= c(16, 17, 15, 3, 4, 8)) +
  geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
               data = en_coord_cont, size =0.5, alpha = 1, colour = "grey30") +
  geom_text(data = en_coord_cont, aes(x = NMDS1+0.1, y = NMDS2+0.03), colour = "black", 
            fontface = "bold", label = row.names(en_coord_cont), size =3) +
  labs(shape="Phase", colour="Reactor") +
  theme(panel.background = element_rect(fill='white', colour='black'), panel.grid.major = element_line(colour = "lightgrey"), text = element_text(size = 15))
#dev.off()

```

# Taxonomy plot - Family
```{r tax plot family}
list_days <- c("R1-1", "R1-2", "R1-3", "R2-1", "R2-2", "R2-3", "R3-1", "R3-2", "R3-3", "2", "6", "10", "14", "18", "22", "28", "40", "52", "54", "64", "76", "78", "88", "90", "100", "102", "112", "114", "124", "126", "136", "138", "144", "146", "152", "154", "160", "162", "168", "170", "176", "178", "180", "182", "184", "186", "192", "194", "200", "202", "208", "210", "216", "218", "224", "226")

y1p <- tax_glom(ps_withoutB6_rarified_withoutFOAM_withoutINOC, taxrank = 'Family') # agglomerate taxa
y3p <- transform_sample_counts(y1p, function(x) x/sum(x)) #get abundance in %
y4p <- psmelt(y3p) # create dataframe from phyloseq object
y4p$Family <- as.character(y4p$Family) #convert to character
y4p$Family[y4p$Abundance < 0.05] <- " Family < 5% abund." #rename genera with < 1% abundance

#set color palette to accommodate the number of genera
colourCount <- length(unique(y4p$Family))
getPalette <- colorRampPalette(brewer.pal(9, "Set1"))

#plot
y4p$Days_operation = factor(y4p$Days_operation, levels= list_days)

# all samples
#png("figures_article/Tax_Family_days.png", width = 10, height = 4, units = "in", res=300)
p_p <- ggplot(data=y4p, aes(x=Days_operation, y=Abundance, fill=Family))
p_p + geom_bar(aes(), stat="identity", position="stack") + 
  facet_wrap(~ Reactor_tax, 
             #nrow = 3, 
             scales = "free", labeller = labeller(.multi_line = FALSE)) +
  scale_fill_manual(values=getPalette(colourCount)) + 
  xlab("Days of operation") + ylab("Relative Abundance") +
# guides(fill=guide_legend(nrow=5)) +
  theme(axis.text.x = element_text(angle=90, size= 8), axis.title.x = element_text(vjust=0), 
        text = element_text(size = 12), legend.position = "bottom")
#dev.off()

```

# Taxonomy plot - Genus
```{r tax plot genus}
y1p <- tax_glom(ps_withoutB6_rarified_withoutFOAM_withoutINOC, taxrank = 'Genus') # agglomerate taxa
y3p <- transform_sample_counts(y1p, function(x) x/sum(x)) #get abundance in %
y4p <- psmelt(y3p) # create dataframe from phyloseq object
y4p$Genus <- as.character(y4p$Genus) #convert to character
y4p$Genus[y4p$Abundance < 0.05] <- " Genus < 5% abund." #rename genera with < 1% abundance

#set color palette to accommodate the number of genera
colourCount = length(unique(y4p$Genus))

#plot
y4p$Days_operation = factor(y4p$Days_operation, levels= list_days)

# all samples
#png("figures_article/Tax_Genus_days.png", width = 10, height = 4, units = "in", res=300)
p_p <- ggplot(data=y4p, aes(x=Days_operation, y=Abundance, fill=Genus))
p_p + geom_bar(aes(), stat="identity", position="stack") + 
  facet_wrap(~ Reactor_tax, 
             #nrow = 3, 
             scales = "free", labeller = labeller(.multi_line = FALSE)) +
  scale_fill_manual(values=getPalette(colourCount)) + 
  xlab("Days of operation") + ylab("Relative Abundance") +
  #  guides(fill=guide_legend(nrow=5)) +
  theme(axis.text.x = element_text(angle=90, size= 8), axis.title.x = element_text(vjust=0),
        text = element_text(size = 10), legend.position = "bottom")
#dev.off()
```

```{r session info}
sessionInfo()
```
